sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  - "lander --pdf DMTN-049.pdf --upload --lsstdoc DMTN-049.tex --env=travis --ltd-product $PRODUCT --handle $HANDLE"
env:
  global:
    # Handle needs to be explicitly set until https://github.com/lsst-sqre/metasrc handles LaTeX inputs
    - HANDLE="DMTN-049"
    - PRODUCT="dmtn-049"
    # LTD Keeper and AWS credentials
    - secure: "bIA3+RJQ1vCCRiC3504X8K/b1t6vIQbplr9bcIMTud7Oqsupi4C5v6PR1qswIxr2VTLJ/1fgB7mxOyWxNHZfLjlJPO3XJ6S+DPI8p+almiIS8pZn/FuvCoJpQbt2qt9SH+rwgGz6nGoOY8h1nLD5dcn7p8n7tFeAz/7UR/XnVRm6cgVPiRjcQ5EL4NB4tlgjgFqCQZ8wymsLKYJtjOv3Rt4sCxl9jg6TweUFTCuSyDttcxSe/8CZab/cHeqbCImg796yf9OKcj/mYmWotk4n4yedF22f6i8S7l8HcP8t+EFr43MMr3/1H3mUehwXHgkTeBQHgrOUiHpNky6pemzDqHTzJWUbnLX+AUcdxYKdFSeSYpvuu0OFXcNRIFBHOFEz2JUTyy7HnLbUYjCX3eBMjGS1u9hFhEB8UscyihAqyOq11v9GBJdXXIIIoF4Lc1upLhp5P8p2LzibqSuZIpyHNKJqquiGCtU+ixRm6WPuiIYwYPaBqxNIh6BqJE+9iLAO9INwui9NU4FWeC98CDS87z8V2IRqg8CGtoKiWBM753dGyQqncXbKh0U5w3lKAu2n06eJBvVDMS3NQLAfIKzfoUYcB4aoNWEV7NlBVk0GLpJXU3fVnCmImad0Q7j688/cpGKHEn2f/ffLJYpl7YXkZ0QyVkO7TCtTuUAVkzvjmHQ="
    - secure: "oP8UGEEpW6D0Q0BaB7PdaZ7pFQjT9UikYaGQdplKgqsuurs5oHG2YC+dKlGlFdMvRHeMeaqFmHoUdJGYS7ezy8sMeiW16N2if/bubnuD2qUSTjk50mrsF/DudS1H6XeDVX+g4FPH4F8jaG4vqG8Q5EEFbnnPKVqUKuOpSNXdFdIpI39/+WorTD4uiF1Ic3oi/CvJ5U29niwR791pUHRdvOsZ9Vpgs2UHhHGTv1eHFEeSd1jULP+zve9kBn3LgcU9fSCEC91DrTKY9CFdt9fb75sHi5KtY6AQP3ONOYrWpIAVL/j+uRmySzMrFcOzYLHCN7nwngw9Q0xsQxr6xQ/gSznP3XXZQjdjNgoLYu/4dp4y6d9ZmSVluombrlzUVxquZk3u94+7XGTNb4YnIK+d+1YHg+Uax07tFZLEBUliY3PoeNrQnPZ4PKZs+iKJhOZKtPJVVuWRKD8F29rovZ2tFXN7l02ILw9WZk4dYsRFxuD1+PFVZdL7aGnBksNU2V4fQRK/PTp4fi5xO73+TJ9oPvENu/OHehQn4iWVdccGwFfrOCvS6H5SzYS3xMcSW7RVvhe22dp2wEyEKWPgzLEjP5a/VtP4lbxJbyRsJ/7JnunspglGvEZxt5/wlNYJQyUCSnNHtuDr4YPUC9YHtUPxewf4r4yrMRR+Njbw6kOiSPM="
